const experiencesProduct = [
    {
        id: 0,
        name: "Northern Lights",
        price: 120,
        instock: 100,
        description: "Northern Lights Tour",
        imgSrc: "images/northern-lights-img.jpg",
    },
    {
        id: 1,
        name: "Three Elves",
        price: 60,
        instock: 100,
        description: "Three Elves Tour",
        imgSrc: "./images/three-elves-img.jpg",
    },
    {
        id: 2,
        name: "Skogafoss",
        price: 80,
        instock: 100,
        description: "Skogafoss Tour",
        imgSrc: "./images/skogafoss-img.jpg",
    },
    {
        id: 3,
        name: "Northern Lights",
        price: 70,
        instock: 100,
        description: "Ice Bergs Tour",
        imgSrc: "./images/ice-bergs-img.jpg",
    },
    {
        id: 4,
        name: "Black Sand",
        price: 40,
        instock: 100,
        description: "Black Sand Tour",
        imgSrc: "./images/northern-lights-img.jpg",
    },
    {
        id: 5,
        name: "Explorer",
        price: 50,
        instock: 100,
        description: "Northern Lights Tour",
        imgSrc: "./images/explorer-img.jpg",
    },
];

const guideProduct = [
    {
        id: 0,
        name: "Rodrigo",
        price: 20,
        instock: 1,
        description: "Rodrigo Guide",
        imgSrc: "./images/guide-rodrigo-img.jpg",
    },
    {
        id: 1,
        name: "Andre",
        price: 30,
        instock: 1,
        description: "Andre",
        imgSrc: "./images/guide-andrei-img.jpg",
    },
    {
        id: 2,
        name: "Anne",
        price: 40,
        instock: 1,
        description: "Anne",
        imgSrc: "./images/guide-anne-img.jpg",
    },
    {
        id: 3,
        name: "Holly",
        price: 50,
        instock: 1,
        description: "Holly",
        imgSrc: "./images/guide-holly-img.jpg",
    },
];
